trigger:
- none

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AKS-Service-Connection'
  resourceGroupName: 'aks-demo-rg'
  location: 'centralus'
  templateFile: './Infrastructure/main.bicep'
  imageRepository: 'azure-vote-front'
  dockerfilePath: '**/Dockerfile'
  dockerRegistryServiceConnection: ''

stages:
- stage: Infrastructure
  displayName: Build Infrastructure
  jobs:  
  - job: Infrastructure 
    displayName: Build Infrastructure
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: '-clusterName $(clusterName) -dnsPrefix $(dnsPrefix) -linuxAdminUsername $(linuxAdminUsername) -sshRSAPublicKey $(SSH_KEY_VAL)'
        deploymentMode: 'Incremental'
        deploymentName: 'DeployPipelineTemplate'
      env:
        SSH_KEY_VAL: '$(ssh_key)'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests'
        path: 'manifests' 


